on:
  push:
    branches:
      - main
      - migration-to-svelte-deploy
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Deploy to VPS
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ vars.VPS_HOST }}
          username: ${{ vars.VPS_USER }}
          key: ${{ vars.VPS_SSH_KEY }}
          script: |
                      cd ~/thefoxxstuff.net
                      git fetch origin
                      git reset --hard origin/migration-to-svelte-deploy
                      docker compose up -d --build --force-recreate
                      docker image prune -f
                      echo "Deploy complete and branches synced!"